---
bibliography: /Users/EC13/Documents/Projects/PRSN/Hazus/Documentation/Written/Markdown/References.bib
titlefont: Times New Roman
mainfont: Times New Roman
fontsize: 12pt
urlcolor: blue
csl: natural-hazards.csl
header-includes:
  - \usepackage{setspace}
  - \usepackage{amsmath} # for \eqref
  - \setlength{\parindent}{4em}
  - \setlength{\parskip}{0.5em}
  - \usepackage{float}
  - \floatplacement{table}{H} #!htbp
output:
  pdf_document:
    number_sections: true
    extra_dependencies: ["booktabs","float"]
    toc: no
  theme: journal  # many options for theme, this one is my favorite.
  highlight: tango  # specifies the syntax highlighting style
  bookdown::pdf_book: 
    keep_tex: true
    number_sections: true
    toc: true
    base_format: rticles::elsevier_article
    citation_package: biblatex
  html_document:
    toc: true # table of content true
    toc_float: true
    toc_depth: 5  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
  word_document:
always_allow_html: true
editor_options: 
  markdown: 
    wrap: 72
---

```{r libraries,echo=FALSE}
library(knitr) 
library(kableExtra)
options(knitr.kable.NA = '')
```

```{=tex}
\begin{center}
\textbf{From Tremors to Tragedy: Quantifying Seismically-Induced Landslide Susceptibility in Puerto Rico for Disaster Preparedness}

\noindent
Elvin Cordero
\end{center}
```
\noindent \textbf{Affiliation:}

\noindent
- Department of Marine Sciences, University of Puerto Rico-Mayagüez, Marine Geology Lab, Isla Magueyes, Lajas, Puerto Rico 00667

\noindent
- Puerto Rico Seismic Network, University of Puerto Rico-Mayagüez, Universidad de Puerto Rico Edificio D Mayagüez, Puerto Rico 00680

\noindent \textbf{Email:} 
[elvin.cordero\@upr.edu](mailto:elvin.cordero@upr.edu){.email}

\noindent \textbf{Research Domain:} Natural Hazards, GIS, Remote Sensing

\noindent \textbf{Funding Information:} 

\noindent \textbf{Date:} `r format(Sys.time(), '%B %d, %Y')`

\noindent \textbf{Keywords:} Hazus, Landslide Susceptibility, Earthquake, Risk Analysis

\noindent \textcolor{red}{\LARGE{DRAFT}}

\pagenumbering{gobble} 

\newpage
```{=latex}
\setcounter{tocdepth}{5}
\tableofcontents
```
\newpage
\pagenumbering{arabic} 
<!-- \doublespacing -->

\newpage
# Introduction

Puerto Rico, a territory characterized by its dynamic geological and seismic activity, stands at the forefront of understanding natural hazards in the Caribbean region. Among these hazards, landslides triggered by seismic events represent a critical intersection of earth surface processes and human vulnerability. This study aims to unravel the complexities of seismically induced landslides in Puerto Rico, providing a comprehensive analysis that bridges the gap between seismology and geomorphology.

The island's unique geological composition, coupled with its location at the boundary of the North American and Caribbean tectonic plates, predisposes it to frequent seismic activity. These seismic events, ranging from minor tremors to significant earthquakes, possess the potential to destabilize slopes and trigger landslides, posing substantial risks to both the population and infrastructure. The devastating impact of the 2020 southwestern Puerto Rico earthquakes underscores the urgency of assessing landslide susceptibility in a seismically active context.

This paper explores the mechanisms by which seismic forces contribute to slope failure, employing a multidisciplinary approach that combines geotechnical analysis, spatial data modeling, and historical event review. By focusing on seismically induced landslides, the study seeks to identify key factors contributing to landslide susceptibility, including seismic intensity, ground motion characteristics, slope angle, lithology, and hydrological conditions.

The overarching goal is to develop a predictive model for landslide susceptibility in Puerto Rico that accounts for seismic triggers. Such a model not only advances our scientific understanding of landslide dynamics but also serves as a crucial tool for disaster risk management, land-use planning, and the development of mitigation strategies to protect vulnerable communities. Through this research, we contribute to a safer and more resilient Puerto Rico, where the risks of seismically induced landslides are understood, anticipated, and managed.

as a proxy for potential soil wetness [@nowickijesseeGlobalEmpiricalModel2018]. 

# Methodology

## Software

The geospatial processing procedures were completed with the R statistical language
[@rcoreteamLanguageEnvironmentStatistical2023a] using spatial toolsets such as the *terra* and *tidyterra* packages [@hernangomezUsingTidyverseTerra2023; @hijmansTerraSpatialData2023]. Polygon drafting and editing was done in the QGIS geographic information system software [@qgisdevelopmentteamQGISGeographicInformation2024].

## Data Requirements

### Peak Ground Velocity (PGV)
Peak Ground Velocity (PGV) measures the maximum speed at which the ground moves at a location during an earthquake, typically expressed in terms of distance per unit time. It is a critical parameter in seismology and earthquake engineering, indicating the intensity of ground motion and its potential to cause structural damage and induce landslides. PGV is used alongside peak ground acceleration (PGA) and spectral acceleration (SA) in seismic hazard analysis to characterize expected ground shaking, informing the design of earthquake-resistant structures and mitigation strategies. High PGV values are associated with increased risk of severe structural damage and slope failures, making accurate PGV estimation vital for risk assessments, building codes, and the development of earthquake preparedness measures. The PGV for three historical earthquake scenarios were used by @ramirez-riveraEarthquakeLossEstimation2016 to estimate earthquake loss; these included the M7.5 Mona Canyon earthquake of 1918, the M7.5 Virgin Island Basin (VIB) earthquake of 1867, and the M~8.0 event that occurred offshore the northern coast of Puerto Rico on May 2, 1787 [@doserHistoricalEarthquakesPuerto2005]. Specified fault geometry and magnitude of the earthquake scenarios from estimates of i) fault dimensions, ii) intensity map, and iii) ground motion [@ramirez-riveraEarthquakeLossEstimation2016] were obtained from publications (Table 1) [@huerfanoSusceptibilidadPuertoRico2003; @mercadoNumericalSimulation19181998; @zahibo1867VirginIsland2003].

### Digital Elevation Model (DEM)
Digital Elevation Models (DEMs) are pivotal in landslide susceptibility analysis, through precise slope gradient calculations and hydrological modeling. DEMs delineate steep terrains at heightened landslide risk and areas susceptible to water-induced soil destabilization. By integrating DEMs with geotechnical data, researchers can quantitatively assess erosion dynamics and structural stability of landforms. The SRTM15+ global bathymetry and topography (15-arc sec resolution) for Puerto Rico was downloaded using the *elevatr* package [@hollisterElevatrAccessElevation2023; @tozerGlobalBathymetryTopography2019]. Slope, $\alpha$, was calculated using the @flemingMachineProcessingLandsat1979 method and eight neighboring cell. Flow direction of water, $Q_{d}$ for each cell was estimated from the direction of the greatest drop in elevation [@hijmansTerraSpatialData2023] and flow accumulation, $A_{s}$, was defined as the sum of flow directions of the surrounding neighbors (Equation \ref{eq:flowAcc}). 

\begin{equation}\label{eq:flowAcc}
  A_{s} = \displaystyle\sum_{n=1}^{8} Q_{d}
\end{equation}

With DEM-derived flow accumulation as a proxy for specific basin area and the slope in radians, the compound topography index (CTI) [@mooreDigitalTerrainModelling1991], also known as the topographical wetness index (TWI) [], was computed using Equation \ref{eq:cti}.

\begin{equation}\label{eq:cti}
  CTI = \ln \left(\frac{A_{s}}{tan(\alpha)}\right)
\end{equation}

The slope angle (degrees) were given landslide susceptibility scores according to the @nadimGlobalLandslideAvalanche2006 categorization of slope data. CTI values were grouped into equal intervals ranging from 0-5 and > 50, each assigned a landslide susceptibility score between zero and 10.

### Land Cover
Land cover significantly influences landslide susceptibility through its modulation of surface hydrological dynamics and slope stability mechanisms. Vegetation, particularly forest cover, enhances soil cohesion via root systems and mitigates surface runoff by facilitating water infiltration, thereby reducing hydraulic pressures on slope materials. Conversely, impervious surfaces amplify runoff, potentially escalating hydraulic stress at slope bases and along drainage paths, increasing susceptibility to landslides. Anthropogenic land cover alterations, such as deforestation and urban development, disrupt natural drainage systems and compromise slope integrity by reducing vegetative stabilization and altering load distributions. Moreover, land cover changes affecting soil erosion rates can directly impact slope stability by modifying soil support and contributing to the accumulation of destabilizing sediments. Regional land cover dataset for Puerto Rico was downloaded from the National Oceanic and Atmospheric Administration's (NOAA) Coastal Change and Analysis Program (CCAP) at 30-m resolution [@noaaofficeforcoastalmanagementCoastalChangeAnalysis]. The CCAP dataset was reclassified following the definitions in the Global Land Cover Map for 2009 (GlobCover2009) [@arinoGlobalLandCover2012]. The landslide susceptibility score was assigned by rating the land cover type from one to 10 (Table ).

### Lithology
Lithology is pivotal in assessing an area's susceptibility to seismically induced landslides, influencing both the mechanical strength and the hydrological behavior of geological materials in response to earthquake forces. The inherent properties of different rock types, such as cohesion, permeability, and susceptibility to weathering, determine their stability under seismic shaking. Weak, unconsolidated, or highly fractured lithologies are particularly prone to slope failures during earthquakes, while lithological contrasts can create potential slip planes. Additionally, certain rock types can amplify seismic waves, further exacerbating landslide risk. Understanding the lithological framework is, therefore, essential for accurate landslide susceptibility assessments in seismically active regions, enabling targeted mitigation strategies to minimize earthquake-induced landslide hazards. Using the geologic map of Puerto Rico produced by @bawiecGeologyGeochemistryGeophysics1998, the geologic descriptions were grouped by lithology (i.e. endogenous, extrusive, or sedimentary rocks) and stratigraphy (e.g. Cenozoic, Mesozoic, etc.) and assigned a landslide susceptibility score following the @nadimGlobalLandslideAvalanche2006 classification scheme adjusted to fit a scale of one to 10 (Table ). 



## Model Development


\newpage
# References



